### ISSUE TITLE
addValueChangeListener is executed on attach

### ISSUE THREAD

**Issue by anasmi** [vaadin/vaadin-date-time-picker-flow#22] opened 2020-03-23 09:27 UTC
Version : 14.2.0.alpha9
Scenario: Define datetimePicker with the value and assign a `addValueChangeListener`.
Expected: the `addValueChangeListener` is not called on attach.
Actual : the change listener is called and `event.isFromClient()` is evaluated to true (which is not the case. Value is set from server).

Code to reproduce: 
```
 DateTimePicker dtp=new DateTimePicker(ldt);
 dtp.setLabel("DatePicker test");
 dtp.setInitialPosition(LocalDate.of(2022,Month.APRIL,3));
 dtp.addValueChangeListener(event->{
          System.out.println(event.getValue() +
                   Is from client: " + event.isFromClient());
           });
 add(dtp);
```

**Comment by Haprog** [comment] 2020-03-30 10:35
I can't reproduce the issue on Vaadin 14.2.0.alpha9 with vaadin-date-time-picker-flow 1.0.0.alpha1 (also tried 1.0.0.alpha2 with no difference).

`setInitialPosition()` is probably not relevant but I tried with and without it (it was removed in the alpha2).

When I just load the page I don't get anything in server console. Only when I change the value by interacting with the component, then I get the message logged to console.

Here's the full snippet I tested with (had to fix a string syntax error and with missing double quote and added the definition for `ldt` variable):
```java
LocalDateTime ldt = LocalDateTime.of(2020, 1, 13, 14, 15);
DateTimePicker dtp = new DateTimePicker(ldt);
dtp.setLabel("DatePicker test");
dtp.setInitialPosition(LocalDate.of(2022, Month.APRIL,3));
dtp.addValueChangeListener(event -> {
    System.out.println("Value: " + event.getValue() +
            ", Is from client: " + event.isFromClient());
});
add(dtp);
```

@anasmi If you can still reproduce this could you share a project zip where it happens?

**Comment by Haprog** [comment] 2020-03-30 12:06
Now I was able to reproduce it and know what is going on.

This only happens when you set a `LocalDateTime` value which contains non-zero seconds (or milliseconds) or if you use e.g. `LocalDateTime.now()`.

This happens because by default the `DateTimePicker` value precision does not include seconds and the client side component automatically corrects the value to remove seconds unless you set a `step` of less than a minute. So the value actually does change in this case (seconds are basically set to 0 if thinking about server side value).

You can avoid the initial value change event by setting the value to a `LocalDateTime` which only defines up to minutes. Or by setting step so that seconds will be shown in the client side too.

``java
// 1
LocalDateTime.now().truncatedTo(ChronoUnit.MINUTES);
// 2
LocalDateTime.of(2020, 1, 13, 14, 15); // No seconds set
// 3
dateTimePicker.setStep(Duration.ofSeconds(1)); // Seconds will be included in client side value too
```

**Comment by Haprog** [comment] 2020-03-30 13:12
This works consistently the same way as TimePicker. Though TimePicker has an additional related bug if setting the value in the constructor (https://github.com/vaadin/vaadin-time-picker-flow/issues/75).

**Comment by Haprog** [comment] 2020-03-30 13:38
Closing this as works as intended (and consistent with `TimePicker` behaviour).

**Closed by Haprog** 2020-03-30 13:38 UTC
