### ISSUE TITLE
Value change events fired even when value is invalid

### ISSUE THREAD

**Issue by vaadin-miki** [vaadin/vaadin-date-time-picker-flow#27] opened 2020-03-23 19:57 UTC
### Code
```
DateTimePicker dateTimePicker = new DateTimePicker(LocalDateTime.now());
dateTimePicker.setMin(LocalDateTime.now().plusWeeks(1));
dateTimePicker.setMax(LocalDateTime.now().plusWeeks(3));
dateTimePicker.addValueChangeListener(event -> {
                    LoggerFactory.getLogger(this.getClass()).warn("Date and time selected {}", event.getValue().format(DateTimeFormatter.ISO_DATE_TIME));
                }
        );
```

### Observed
```
WARN org.vaadin.miki.MainView - Date and time selected 2020-03-23T21:55:00
WARN org.vaadin.miki.MainView - Date and time selected 2020-03-30T21:55:00
WARN org.vaadin.miki.MainView - Date and time selected 2020-03-30T22:55:00
WARN org.vaadin.miki.MainView - Date and time selected 2002-02-10T22:55:00
```

The first log message is fired when component is created. See #22.
The last log message is fired when I manually typed date to outside of the allowed range.

### Expected

Given that at least some validation is done on the client side (as the component magically turns red when the value is incorrect), I would expect server-side `ValueChangeEvent` *not* fired when the value is invalid.

**Comment by Haprog** [comment] 2020-03-30 11:41
Imo this works as expected (whenever `value` property changes on client side it also triggers a value change event on server) when doing it like this (without Binder). This is also currently consistent compared to `DatePicker` which works the same way.

The whole situation with validation and Binder is not ideal though but it's not an issue with a specific component. See related issue https://github.com/vaadin/components-team-tasks/issues/489

**Comment by Haprog** [comment] 2020-03-30 13:55
Closing this as works as intended.

**Closed by Haprog** 2020-03-30 13:55 UTC
