### ISSUE TITLE
Binder's bean reports an old value in the `addValueChangeListener` 

### ISSUE THREAD

**Issue by anasmi** [vaadin/vaadin-date-time-picker-flow#24] opened 2020-03-23 10:36 UTC
**Version** : 14.2.0.alpha9
**Scenario** : Select 08.04.2019 in DatePicker part. The binder validation is passed and value in 
    DateTimePicker updated. Nevertheless, the `valueChangeListener` reports the old value for a Bean
**Expected** output in listener: 2019-04-08T15:15; Person value : 2019-04-08T15:15
**Actual**:2019-04-**08**T15:15; Person value : 2019-04-**23**T15:15

----

**Code to reproduce:**
```          
Binder<Person> binder=new Binder<>(Person.class);
Person personTest=new Person();
LocalDateTime ldt=LocalDateTime.of(2019, Month.APRIL,23,15,15,35);
personTest.setMeeting(ldt);

DateTimePicker dtp=new DateTimePicker();
dtp.setLabel("DatePicker test");
dtp.addValueChangeListener(event->{
      System.out.println(event.getValue() + "; Person value : " + personTest.getMeeting());
 });
binder.setBean(personTest);
binder.forField(dtp).withValidator(e->e.isBefore(LocalDateTime.now()), "The current date should be before").asRequired().bind(Person::getMeeting,Person::setMeeting);
```

**Comment by Haprog** [comment] 2020-03-30 11:03
@anasmi I have verified it works as you describe but if you change the source code order to set the value change listener after configuring binder, then it will work as you expect.

I assume this works as intended since there's no special handling of binder in DateTimePicker and it probably works the same in all other components too. Or do you know of any other component which works differently in this kind of case?

**Comment by Haprog** [comment] 2020-03-30 13:54
I have tested that `DatePicker` works exactly the same as this (with `addValueChangeListener()` before or after binder configuration).

Closing this as works as intended (and consistent with `DatePicker`).

**Closed by Haprog** 2020-03-30 13:54 UTC

**Comment by anasmi** [comment] 2020-04-02 05:35
> I have verified it works as you describe but if you change the source code order to set the value change listener after configuring binder, then it will work as you expect.

@Haprog Well, as a developer I still see this is a bug. I don't understand why I should remember the order of the things?

**Comment by Haprog** [comment] 2020-04-04 18:35
Imo it's logical that Binder also listens to value change and if you set a value change listener before configuring Binder then your value change listener runs before Binder's. And depending on what you want to do you may want to do something before or after Binder has done its work. At least I expect value change listeners to run in the order that they were added (though I understand here it's not explicitly visible from code if Binder is using a value change listener or not)

If you think Binder should always do its work before any user added value change listeners then you should probably open an issue about it at https://github.com/vaadin/flow/issues

I'm not sure if this is well documented or not, so it might be a documentation issue with Flow/Binder too.
